### ISSUE TITLE
with_lock with forced unlock

### ISSUE THREAD

**Issue by sld** [kenn/redis-mutex#16]
Hi!
Thanks for the nice gem.

I have a question about this part of code: https://github.com/kenn/redis-mutex/blob/master/lib/redis_mutex.rb#L81-L82

If method will raise an exception inside `with_lock` block then the lock will still exist until expire_at time.
What do you think about changing `with_lock` function to handle `force` argument?
Or maybe `unlock(true)` will be better there?

**Comment by kenn** [comment]
It deletes the lock when and only when you are (still) the owner of it. You can't delete locks that you don't own.
