### ISSUE TITLE
RedisMutex.with_lock multiple locks

### ISSUE THREAD

**Issue by acegilz** [kenn/redis-mutex#19]
Let's suppose I want to use not only user, but also event as locking params, what would be the best way?
I was thinking something like the following, but it would be better if I can combine

```ruby
RedisMutex.with_lock(user) do
   RedisMutex.with_lock(event) do
      ##SOME STUFF
   end
end
```

**Comment by kenn** [comment]
Nested blocks should be fine. Just be careful about the deadlock.

In a general sense, lock ordering is important - see http://tutorials.jenkov.com/java-concurrency/deadlock-prevention.html#ordering
