### ISSUE TITLE
How is this possible?

### ISSUE THREAD

**Issue by acegilz** [kenn/redis-mutex#23]
I have my update_attributes under a redis block:

```ruby
        mutex = RedisMutex.new(exposure, block: 30, sleep: 0.1)
        if mutex.lock
          exposure.update_attributes(amount: exp) ###line 103
          mutex.unlock
        end
```

If I get simultaneous requests on this method I receive the deadlock message:

```
Stack trace[Show framework code]
ActiveRecord::StatementInvalid: Deadlock found when trying to get lock; try restarting transaction
…/website/releases/20151218191556/app/models/autopay.rb:  103:in `aux_calculate'

```

Line 103 is the update_attributes line. How the hell it can enter inside the block but at the same time the attribute is locked, even if I have a bug on my code and I'm locking this row elsewhere, it wouln't enter the blockcode, so how is this deadlock even possible???

**Comment by kenn** [comment]
Deadlock on the database has nothing to do with redis-mutex.

Deadlock 101: it can occur whenever a) it writes in a transaction, and b) it writes to multiple tables and/or records in a different order. 

Also, if you have a deadlock that means you've successfully obtained the mutex-lock, and it's just blocking at the database level. In other words, a database transaction **is** a mutex and I have no idea what you are trying to do with redis-mutex here.

- As a general rule, the more lines of code in a transaction, the more likely you have deadlocks
- Always access objects in the same order (trans1: A->B, trans2: B->A and you get a deadlock)

I guess your code is inside a transaction or a callback (e.g. `after_create`)?

**Comment by acegilz** [comment]
Hmm so I may be missing something here...

I use this gem to protect me against deadlocks (I am using it for some months already and appeared to be working like that), assuring that the record will only be updated if Redis-Mutex could successfully get a lock on it and if it doesn't the record won't be updated >> no deadlock.

The point that I'm not understanding here is how could it be giving deadlock if everywhere on the code where I call update_attributes it requires exclusivity via redis-mutex?

From what I understand, if this deadlock is giving it only means that simultaneously the record was called for update simultaneously >> that means Redis-Mutex failed since I lock every row before update..

**Comment by kenn** [comment]
Your understanding about deadlock is wrong. I already mentioned what a deadlock is, it occurs in a TRANSACTION where the code touches MULTIPLE objects in a different ORDER. Read my comments more carefully, or just read some books or take a class about SQL.

**Comment by kenn** [comment]
One free advice: Most cases will be solved by trying to get an exclusive lock (SELECT ... FOR UPDATE) on the user record (or equivalent owner of the transaction) at the very beginning of the transaction. Because it ensures that other transactions cannot proceed from there.

Your approach to use redis-mutex to solve DB problems is wrong - DBs have solutions for that.

```ruby
transaction do
  user.lock!
  ...
end
```

or

```ruby
after_create: :big_callback

def big_callback
  user.lock!
  ...
end
```

**Comment by acegilz** [comment]
I know that databases have solutions for that, however I think that the approach used by redis-mutex is precisely by ensuring exclusivity by locking the record and going further only if  the database could get a lock on the requested record - after the  `if mutex.lock`

On the other end, I think that it protected not via record locking but also against multi-threding issues, example: http://stackoverflow.com/a/24567438/4126551

Yes, almost an year have passed an I am still fighting with this...

**Comment by kenn** [comment]
If you try `user.lock!` (so called "pessimistic locking", or `SELECT ... FOR UPDATE`), the thread wait on that line for the lock to be released. It works exactly the same way as you described. The answer you linked is wrong - a database lock is the most reliable source of exclusivity, and redis-mutex is an attempt to emulate that.
