### ISSUE TITLE
Missing Mutex.get('<mutex_name>') method

### ISSUE THREAD

**Issue by shanys8** [kenn/redis-mutex#24]
Hello

I am using redis-mutex gem and encountered with some issue - 
When I need to lock the mutex at one context and unlock it in a different context I have to create the mutex again with the same name (I can tell whether it's locked or not) but I cannot unlock the new instance I created.
I think a Mutex.get method will solve this issue.
Am I missing something?

Thanks

**Comment by kenn** [comment]
`Mutex.get('<mutex_name>')` is not race-proof. By the time you want to take action (unlock) on it, a different owner might have taken over the key. It all depends on your use case, but I would discourage that kind of API.

The way redis-mutex confirms if you're still the owner upon unlock is by comparing the timestamp - it's not perfect but works most of the time.

If you're aware of the risk, you could always dive into internals and do the same, or `Marshal.dump` to pass the object over the wire.

**Comment by shanys8** [comment]
Ok thanks.
