### ISSUE TITLE
Detecting a lock inside a lock with the same key?

### ISSUE THREAD

**Issue by jaydattc** [kenn/redis-mutex#39]
We have somewhat of a large codebase where we're trying to maintain some type of mutex between a lot of services.
Where we have run into the problem of a mutex being called inside a mutex with the same key.
Hence, it runs into a deadlock and waits for the entire lock to expire.

```
Redis::Mutex.new(unique_identifier_key).with_lock do
  # some_method might again call the lock
  SomeOtherClass.some_method(unique_identifier_key)
end

class SomeOtherClass
  class << self
    def some_method
      Redis::Mutex.new(unique_identifier_key).with_lock do
        # some work
      end
    end
  end
end
```

The above has been fixed for now at the codebase level.
But in the future, we can do something here to avoid deadlocking the child lock.

**Comment by kenn** [comment]
Sounds like it's a user code issue? Is there anything the library can help with?

**Comment by kenn** [comment]
Closing now but feel free to reopen when you have a suggestion
